# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/EGO1_Student/OV7725_VGA/project_3/project_3.srcs/sources_1/bd/cap_buffer/ip/cap_buffer_blk_mem_gen_0_0/cap_buffer_blk_mem_gen_0_0.xci
# IP: The module: 'cap_buffer_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EGO1_Student/OV7725_VGA/project_3/project_3.srcs/sources_1/bd/cap_buffer/ip/cap_buffer_blk_mem_gen_0_0/cap_buffer_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cap_buffer_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/EGO1_Student/OV7725_VGA/project_3/project_3.srcs/sources_1/bd/cap_buffer/ip/cap_buffer_blk_mem_gen_0_0/cap_buffer_blk_mem_gen_0_0.xci
# IP: The module: 'cap_buffer_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EGO1_Student/OV7725_VGA/project_3/project_3.srcs/sources_1/bd/cap_buffer/ip/cap_buffer_blk_mem_gen_0_0/cap_buffer_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cap_buffer_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
