set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property PACKAGE_PIN F5 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN C6 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN C5 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN B7 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN B6 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN A6 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN A5 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN D8 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN C7 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN E6 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN E5 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN E7 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN D7 [get_ports hsync]
set_property PACKAGE_PIN C4 [get_ports vsync]

set_property IOSTANDARD LVCMOS33 [get_ports sys_rst]
set_property PACKAGE_PIN R1 [get_ports sys_rst]



set_property IOSTANDARD LVCMOS33 [get_ports OV7670_XCLK]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7670_D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7670_D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7670_D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7670_D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7670_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7670_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7670_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OV7670_D[0]}]
set_property PACKAGE_PIN G17 [get_ports OV7670_SIOC]
set_property PACKAGE_PIN J13 [get_ports OV7670_VSYNC]
set_property PACKAGE_PIN D17 [get_ports OV7670_PCLK]
set_property PACKAGE_PIN G14 [get_ports {OV7670_D[7]}]
set_property PACKAGE_PIN F16 [get_ports {OV7670_D[5]}]
set_property PACKAGE_PIN G16 [get_ports {OV7670_D[3]}]
set_property PACKAGE_PIN C15 [get_ports {OV7670_D[1]}]
set_property PACKAGE_PIN E16 [get_ports OV7670_RESET]
set_property PACKAGE_PIN K2 [get_ports ERROR_LED]
set_property IOSTANDARD LVCMOS33 [get_ports OV7670_VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports OV7670_SIOD]
set_property IOSTANDARD LVCMOS33 [get_ports OV7670_SIOC]
set_property IOSTANDARD LVCMOS33 [get_ports OV7670_RESET]
set_property IOSTANDARD LVCMOS33 [get_ports OV7670_PWDN]
set_property IOSTANDARD LVCMOS33 [get_ports OV7670_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports OV7670_HREF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets OV7670_PCLK_IBUF]
set_property PULLUP true [get_ports OV7670_SIOD]
set_property IOSTANDARD LVCMOS33 [get_ports ERROR_LED]


set_property PACKAGE_PIN H17 [get_ports OV7670_SIOD]
set_property PACKAGE_PIN K13 [get_ports OV7670_HREF]
set_property PACKAGE_PIN E17 [get_ports OV7670_XCLK]
set_property PACKAGE_PIN H14 [get_ports {OV7670_D[6]}]
set_property PACKAGE_PIN F15 [get_ports {OV7670_D[4]}]
set_property PACKAGE_PIN H16 [get_ports {OV7670_D[2]}]
set_property PACKAGE_PIN D15 [get_ports {OV7670_D[0]}]
set_property PACKAGE_PIN E15 [get_ports OV7670_PWDN]



set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property PACKAGE_PIN K1 [get_ports led]

set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property PACKAGE_PIN J2 [get_ports led2]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets OV7670_VSYNC_IBUF]


# Clock signal
#Bank = 34, Pin name = ,					Sch name = CLK100MHZ
#set_property PACKAGE_PIN P17 [get_ports clk_pin]
#set_property IOSTANDARD LVCMOS33 [get_ports clk_pin]
#create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk_pin]

# Switches
set_property PACKAGE_PIN N4 [get_ports lb_sel_pin]
set_property IOSTANDARD LVCMOS33 [get_ports lb_sel_pin]

#Buttons
#Bank = 14, Pin name = ,					Sch name = BTNC
set_property PACKAGE_PIN U4 [get_ports rst_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rst_pin]

# LEDs
#set_property PACKAGE_PIN F6 [get_ports {led_pins[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[0]}]
#set_property PACKAGE_PIN G4 [get_ports {led_pins[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[1]}]
#set_property PACKAGE_PIN G3 [get_ports {led_pins[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[2]}]
#set_property PACKAGE_PIN J4 [get_ports {led_pins[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[3]}]
#set_property PACKAGE_PIN H4 [get_ports {led_pins[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[4]}]
#set_property PACKAGE_PIN J3 [get_ports {led_pins[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[5]}]
#set_property PACKAGE_PIN A15 [get_ports {led_pins[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[6]}]
#set_property PACKAGE_PIN A16 [get_ports {led_pins[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[7]}]
#set_property PACKAGE_PIN A13 [get_ports {led_pins[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[8]}]
#set_property PACKAGE_PIN H6 [get_ports {led_pins[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[9]}]
#set_property PACKAGE_PIN H5 [get_ports {led_pins[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[10]}]
#set_property PACKAGE_PIN J5 [get_ports {led_pins[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[11]}]
#set_property PACKAGE_PIN K6 [get_ports {led_pins[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[12]}]
#set_property PACKAGE_PIN L1 [get_ports {led_pins[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[13]}]
#set_property PACKAGE_PIN M1 [get_ports {led_pins[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[14]}]
#set_property PACKAGE_PIN K3 [get_ports {led_pins[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_pins[15]}]

##USB-RS232 Interface
##Bank = 16, Pin name = ,					Sch name = UART_TXD_IN
set_property PACKAGE_PIN L3 [get_ports rxd_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rxd_pin]
#Bank = 16, Pin name = ,					Sch name = UART_RXD_OUT
set_property PACKAGE_PIN N2 [get_ports txd_pin]
set_property IOSTANDARD LVCMOS33 [get_ports txd_pin]
# BT
set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports {sw_pin[0]}]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports {sw_pin[1]}]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports {sw_pin[2]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports {sw_pin[3]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {sw_pin[4]}]


set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports bt_pw_on]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports bt_master_slave]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports bt_sw_hw]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports bt_rst_n]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports bt_sw]

#7 segment display
set_property PACKAGE_PIN B4 [get_ports {seg7_0_7bit[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_7bit[0]}]
set_property PACKAGE_PIN A4 [get_ports {seg7_0_7bit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_7bit[1]}]
set_property PACKAGE_PIN A3 [get_ports {seg7_0_7bit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_7bit[2]}]
set_property PACKAGE_PIN B1 [get_ports {seg7_0_7bit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_7bit[3]}]
set_property PACKAGE_PIN A1 [get_ports {seg7_0_7bit[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_7bit[4]}]
set_property PACKAGE_PIN B3 [get_ports {seg7_0_7bit[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_7bit[5]}]
set_property PACKAGE_PIN B2 [get_ports {seg7_0_7bit[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_7bit[6]}]
set_property PACKAGE_PIN D5 [get_ports seg7_0_dp]
set_property IOSTANDARD LVCMOS33 [get_ports seg7_0_dp]

set_property PACKAGE_PIN G2 [get_ports {seg7_0_an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_an[0]}]
set_property PACKAGE_PIN C2 [get_ports {seg7_0_an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_an[1]}]
set_property PACKAGE_PIN C1 [get_ports {seg7_0_an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_an[2]}]
set_property PACKAGE_PIN H1 [get_ports {seg7_0_an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_0_an[3]}]

set_property PACKAGE_PIN D4 [get_ports {seg7_1_7bit[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_7bit[0]}]
set_property PACKAGE_PIN E3 [get_ports {seg7_1_7bit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_7bit[1]}]
set_property PACKAGE_PIN D3 [get_ports {seg7_1_7bit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_7bit[2]}]
set_property PACKAGE_PIN F4 [get_ports {seg7_1_7bit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_7bit[3]}]
set_property PACKAGE_PIN F3 [get_ports {seg7_1_7bit[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_7bit[4]}]
set_property PACKAGE_PIN E2 [get_ports {seg7_1_7bit[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_7bit[5]}]
set_property PACKAGE_PIN D2 [get_ports {seg7_1_7bit[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_7bit[6]}]

set_property PACKAGE_PIN H2 [get_ports seg7_1_dp]
set_property IOSTANDARD LVCMOS33 [get_ports seg7_1_dp]

set_property PACKAGE_PIN G1 [get_ports {seg7_1_an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_an[0]}]
set_property PACKAGE_PIN F1 [get_ports {seg7_1_an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_an[1]}]
set_property PACKAGE_PIN E1 [get_ports {seg7_1_an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_an[2]}]
set_property PACKAGE_PIN G6 [get_ports {seg7_1_an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_1_an[3]}]

#set_property IOB TRUE [all_fanin -only_cells -startpoints_only -flat [all_outputs]]

set_property IOSTANDARD LVCMOS33 [get_ports t]
set_property PACKAGE_PIN B16 [get_ports t]

