# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/vivado/project/homework/project_3/project_3.cache/wt [current_project]
set_property parent.project_path E:/vivado/project/homework/project_3/project_3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/vivado/project/homework/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/vivado/project/homework/project_3/project_3.srcs/sources_1/new/CAPTURE.v
  E:/vivado/project/homework/project_3/project_3.srcs/sources_1/new/DPRAM_wrapper.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/bt_uart.v
  E:/vivado/project/homework/project_3/project_3.srcs/sources_1/new/cfg_ov.v
  E:/vivado/project/homework/project_3/project_3.srcs/sources_1/new/cfg_regs.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/clk_div.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/clk_gen.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/cmd_parse.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/debouncer.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/lb_ctl.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/meta_harden.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/reset_bridge.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/resp_gen.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/rst_gen.v
  E:/vivado/project/homework/project_3/project_3.srcs/sources_1/new/sccb_sender.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/seg7decimal.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/to_bcd.v
  E:/vivado/project/homework/project_3/project_3.srcs/sources_1/imports/sources/top_flyinglogo.v
  E:/vivado/project/homework/sources_1/imports/project/turn_10d/turn_10d.srcs/sources_1/new/turn_10d.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/uart_baud_gen.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/uart_rx.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/uart_rx_ctl.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/uart_tx.v
  E:/vivado/project/homework/sources_1/imports/project/source/lab7/uart_tx_ctl.v
  E:/vivado/project/homework/project_3/project_3.srcs/sources_1/imports/sources/vga_timing.v
  E:/vivado/project/homework/project_3/project_3.srcs/sources_1/new/all_top.v
}
add_files E:/vivado/project/homework/project_3/project_3.srcs/sources_1/bd/cap_buffer/cap_buffer.bd
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/project_3/project_3.srcs/sources_1/bd/cap_buffer/ip/cap_buffer_blk_mem_gen_0_0/cap_buffer_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/vivado/project/homework/project_3/project_3.srcs/sources_1/bd/cap_buffer/cap_buffer_ooc.xdc]
set_property is_locked true [get_files E:/vivado/project/homework/project_3/project_3.srcs/sources_1/bd/cap_buffer/cap_buffer.bd]

read_ip -quiet E:/vivado/project/homework/sources_1/ip/clk_core/clk_core.xci
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/sources_1/ip/clk_core/clk_core_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/sources_1/ip/clk_core/clk_core.xdc]
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/sources_1/ip/clk_core/clk_core_ooc.xdc]
set_property is_locked true [get_files E:/vivado/project/homework/sources_1/ip/clk_core/clk_core.xci]

read_ip -quiet E:/vivado/project/homework/project_3/project_3.srcs/sources_1/ip/dcm_25m/dcm_25m.xci
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/project_3/project_3.srcs/sources_1/ip/dcm_25m/dcm_25m_board.xdc]
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/project_3/project_3.srcs/sources_1/ip/dcm_25m/dcm_25m.xdc]
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/project_3/project_3.srcs/sources_1/ip/dcm_25m/dcm_25m_ooc.xdc]
set_property is_locked true [get_files E:/vivado/project/homework/project_3/project_3.srcs/sources_1/ip/dcm_25m/dcm_25m.xci]

read_ip -quiet E:/vivado/project/homework/sources_1/ip/char_fifo/char_fifo.xci
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/sources_1/ip/char_fifo/char_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/sources_1/ip/char_fifo/char_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/vivado/project/homework/sources_1/ip/char_fifo/char_fifo_ooc.xdc]
set_property is_locked true [get_files E:/vivado/project/homework/sources_1/ip/char_fifo/char_fifo.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivado/project/homework/project_3/project_3.srcs/constrs_1/imports/xdc/display_vga.xdc
set_property used_in_implementation false [get_files E:/vivado/project/homework/project_3/project_3.srcs/constrs_1/imports/xdc/display_vga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top all_top -part xc7a35tcsg324-1


write_checkpoint -force -noxdef all_top.dcp

catch { report_utilization -file all_top_utilization_synth.rpt -pb all_top_utilization_synth.pb }
