# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/display_vga.xdc

# Block Designs: bd/cap_buffer/cap_buffer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cap_buffer || ORIG_REF_NAME==cap_buffer}]

# IP: bd/cap_buffer/ip/cap_buffer_blk_mem_gen_0_0/cap_buffer_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cap_buffer_blk_mem_gen_0_0 || ORIG_REF_NAME==cap_buffer_blk_mem_gen_0_0}]

# IP: E:/vivado/project/homework/sources_1/ip/clk_core/clk_core.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_core || ORIG_REF_NAME==clk_core}]

# XDC: bd/cap_buffer/cap_buffer_ooc.xdc
